### ISSUE TITLE
WPML String Translations Compatibility: Stale PHP files after MO files are updated

### ISSUE THREAD

**Issue by Kilbourne** [swissspidy/performant-translations#124]
Hi!
The wpml-string-translations plugin generates mo files dynamically. When a mo file that was already converted to php is updated, the corresponding php is not updated. 
The relevant code for this should be here: wpml-string-translation/classes/translation-files/UpdateHooks.php
The solution would be simpler if Wpml adds an hook to intercept file updates.

**Comment by swissspidy** [comment]
Thanks for your report. Unfortunately there is indeed no suitable hook inside that class to intercept updates. For example, Loco Translate has `loco_file_written` for this use case.

I suggest you to report this enhancement to WPML so they can add this. Until then there is not really something that can be done in this plugin.

In the meantime you could use the `performant_translations_preferred_format` filter to disable usage of PHP files for translations. You should still get a bit of a speed improvement, but not as much.

**Comment by Kilbourne** [comment]
Thanks for checking this.
Probably it would be better that you ask the additional hook, leveraging the fact this is by the Wp core performance team ( and will merged inside the core in the future).
As there's no public repository, i will have to pass through the support wall, and it could not be really prioritized. Maybe you are also able to find in the community a direct contact to their dev team .
This issue IMO deserves to be in the readme, where it states the plugin is compatible with major ML plugins( being wpml the most widespread and this feature their major one related to MO files)

( About my personal use case, i'm currently deleting the stale php files manually, but will probably soon patch wpml to add the hook and regenerate. I will not revert to MO files, as there's too much an improvement with the php version - thank you for this )

**Comment by swissspidy** [comment]
cc @diiegopereira — Diego, would it be possible to add a `do_action()` call inside the `UpdateHooks` class so that this plugin here can update the PHP translation files whenever an MO file is updated?

**Comment by diiegopereira** [comment]
@swissspidy sure! I created a ticket in our internal system asking to include this hook.
I will update here as soon as I have news.

**Comment by diiegopereira** [comment]
@swissspidy @Kilbourne we got an update from our development team:

> I've added the hook wpml_st_translation_file_updated in 3 different places where we write .mo files:
> 
> I've also added the following line in the file lib/class/performant-translations.php from Performant Translations Plugin:
`add_action( 'wpml_st_translation_file_updated', array( __CLASS__, 'regenerate_translation_file' ) );`

> This works well and re-generate the PHP files properly.
It will be released with WPML String Translation 3.2.9, scheduled now for 8th January.

**Comment by swissspidy** [comment]
This is awesome, thanks a bunch!

I'll merge this into the plugin right away so that this works automatically once the new WPML String Translation version is out.

**Comment by Kilbourne** [comment]
@swissspidy when the next version will be released?
