### ISSUE TITLE
Use WP Filesystem for creating translation files

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/performant-translations#48]
Automatically available when updating translations.

How to do this in a decoupled way?

Related: #6

Probably overkill to do this in the first place, might not be needed

**Comment by soderlind** [comment]
Yes, it might be an overkill but I do it like this: https://github.com/soderlind/a-faster-load-textdomain/blob/main/a-faster-load-textdomain.php#L120-L125

**Comment by swissspidy** [comment]
Thanks for sharing. In theory it should be relatively straightforward to implement this in this project, however the underlying Ginger MO library has been originally built in a platform-agnostic way, i.e. it's not aware of or dependent on any WordPress functions like `WP_Filesystem()`.

Changing that would require quite the overhaul of the entire architecture, either with some dependency injection or giving up on the platform-agnostic nature of the library. See also #6.
