### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/performant-translations#59]
Add explanation how it works, how to clean up data (uninstall), etc.

**Comment by tomxygen** [comment]
I'm not a developer but a WordPress user and I'm excited to see that work has begun to make WordPress international.
However, I'm not sure I understand how this plugin works.
Is this plugin supposed to help wordpress become multilingual (something like WPML: one website, translated in multiple language deepening on visitors' preference)?
or is it for the backend only?

**Comment by swissspidy** [comment]
This plugin helps to make WordPress sites faster which are using a language other than English US. A recent [performance analysis](https://make.wordpress.org/core/2023/07/24/i18n-performance-analysis/) showed that translated WordPress sites are much slower due to additional overhead of loading translations.

The Performant Translations plugin uses a novel approach to loading translations, reducing this overhead and making translated websites (whether they use 1 language or multiple languages) faster.

So if you're website is in Italian, simply activate this plugin to make it faster!

Hope that clarifies things a bit :)

**Comment by tomxygen** [comment]
Thank you! Now it's clear.
