### ISSUE TITLE
Question: Is this tested with common multilingual plugins?

### ISSUE THREAD

**Issue by Zodiac1978** [swissspidy/performant-translations#60]
At first: Thank you so much for tackling this i18n performance issue with your plugin. Much appreciated! 

Before a core solution comes with phase 4, multilingual sites need a plugin to handle multiple languages. Does this plugin work with one or more of them? Is this already tested?

Weglot, TranslatePress, Polylang, WPML, ...

Thanks in advance!

**Comment by swissspidy** [comment]
Yes, this plugin has been successfully tested with all 4 of these plugins on local, non-production websites.

With WPML there were some edge cases leading to errors, but #64 resolves this. A new version 1.0.1 will be released soon for it.

**Comment by oldrup** [comment]
How about translation plugins like Loco Translate? A quick spin on my site, indicated translations performed _after_ the installation of the Performant Translations plugins, are not being used. Disabling Performant Translations, and the translation kicks in. Enabling Performant Translation, and I'm back at the old version.

Is there a way to "purge" the optimized translations created by Performant Translations?

**Comment by swissspidy** [comment]
> How about translation plugins like Loco Translate?
> Is there a way to "purge" the optimized translations created by Performant Translations?

Great question. #62 improves compatibility with Loco Translate and does exactly that.

Will add this to the next 1.0.1 release.
