### ISSUE TITLE
No text after activating the plugin

### ISSUE THREAD

**Issue by majiix** [swissspidy/performant-translations#63]
Hi,
Just after activating the plugin i saw some parts of wordpress admin with no text in it. as you can see in the image below the woocommerce section in dashboard is facing this issue.

![perf](https://github.com/swissspidy/performant-translations/assets/6815416/69f6c0b1-9e32-487a-9f8e-cea68c592f1e)

**Comment by majiix** [comment]
> What is this a screenshot of? How can I see this screen?

This is in wordpress dashboard. The woocommerce status widget and at a glance widget. The website is in Persian language.

![01](https://github.com/swissspidy/performant-translations/assets/6815416/90bb28be-9dbb-4e49-b57f-c8dcb03c3867)
![02](https://github.com/swissspidy/performant-translations/assets/6815416/c2ee4b56-b1d9-46ca-905f-df0037b61dc1)

**Comment by swissspidy** [comment]
Ah, Persian 💡 

Then I know what's up. #64 should solve this.

Can you give this development version a try to see if it resolves the issue for you?

[performant-translations-1.0.1-alpha.zip](https://github.com/swissspidy/performant-translations/files/12478538/performant-translations-1.0.1-alpha.zip)

**Comment by majiix** [comment]
Yup, It's working fine with this one. 

> Ah, Persian 💡
> 
> Then I know what's up. #64 should solve this.
> 
> Can you give this development version a try to see if it resolves the issue for you?
> 
> [performant-translations.zip](https://github.com/swissspidy/performant-translations/files/12478549/performant-translations.zip)

**Comment by swissspidy** [comment]
Awesome, thanks for your quick feedback! I'll get this properly released ASAP
