### ISSUE TITLE
Performance Test For bn_BD Language

### ISSUE THREAD

**Issue by devmuhib009** [swissspidy/performant-translations#76]
I installed the [plugins](https://make.wordpress.org/core/2023/09/05/call-for-testing-performant-translations/) and tested on my local site for bn_BD language. I am adding screenshots for your consideration.

[Before activating the translation performance plugins:](https://ibb.co/ynmPRXc)

![before-activating-plugins](https://github.com/swissspidy/performant-translations/assets/841956/5c6da81b-7d4d-492e-97f9-0d87644e0e38)

[After activating the plugins:](https://ibb.co/gTBkw48)

![after-activating-plugins](https://github.com/swissspidy/performant-translations/assets/841956/1580466a-efb7-40db-9e45-5424119e0f61)

**Comment by swissspidy** [comment]
Thanks for sharing, much appreciated!

Since these are two different pages, what are the before/after numbers if you check the dashboard or the homepage two times?

**Comment by devmuhib009** [comment]
I just checked dashboard before activating the plugins and the number is :  3.98s  47.0MB  0.14s  77Q
After activating it's : 0.92s  42.9MB  0.04s  77Q

**Comment by devmuhib009** [comment]
In home page
Before activating the plugins: 1.95s  44.3MB  0.02s  46Q
After activating the plugins: 1.18s  43.3MB  0.11s  54Q

**Comment by devmuhib009** [comment]
2nd Time Home Page
Before Activating: 1.03s  44.3MB  0.04s  46Q
After Activating:  0.88s  42.2MB  0.02s  46Q

**Comment by swissspidy** [comment]
Very impressive savings! That‘s how it should be! :)

**Comment by devmuhib009** [comment]
Thanks a lot
